CREATE TABLE watteco_registro_consumo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataRegistro DATE NOT NULL,
    consumo NUMBER NOT NULL,
    usuario_id NUMBER,
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES watteco_usuario(id)
);