CREATE TABLE watteco_missao (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    descricao VARCHAR2(255) NOT NULL,
    pontos NUMBER NOT NULL,
    meta VARCHAR2(255) NOT NULL
);